#!/usr/bin/env python3
"""
Адаптер для Android (через Termux и Material You).
Вдохновлено https://github.com/FrancescoCaracciolo/material-you-colors
"""
import json
import subprocess
from pathlib import Path
from base_adapter import BaseAdapter
from cross_themes.utils.logger import setup_logger

logger = setup_logger()


class AndroidAdapter(BaseAdapter):
    def __init__(self):
        super().__init__()
        self.termux_colors_dir = Path.home() / '.termux'
        self.material_you_script = self.config_dir / 'apply_material_you.py'

    def apply_colors(self, theme_data):
        """Применение Material You темы на Android."""
        try:
            # 1. Применение цветов в Termux
            self._apply_termux_colors(theme_data)

            # 2. Создание Material You темы (если доступно)
            self._create_material_you_theme(theme_data)

            # 3. Применение через Monet (Android 12+)
            self._apply_monet_engine(theme_data)

            logger.info("Цвета применены для Android")
            return True

        except Exception as e:
            logger.error(f"Ошибка применения темы Android: {e}")
            return False

    def _apply_termux_colors(self, theme_data):
        """Применение цветов в Termux."""
        colors_file = self.termux_colors_dir / 'colors.properties'

        colors_content = f"""# Termux color scheme generated by Theme Installer
background={theme_data['background']}
foreground={theme_data['on_background']}
cursor={theme_data['primary']}
color0=#000000
color1=#ff5555
color2={theme_data['success']}
color3={theme_data['warning']}
color4={theme_data['primary']}
color5={theme_data['accent_colors'][0] if theme_data['accent_colors'] else '#9b59b6'}
color6={theme_data['info']}
color7=#bbbbbb
color8=#555555
color9=#ff6b6b
color10={theme_data['success'].replace('#', '#88')}
color11={theme_data['warning'].replace('#', '#88')}
color12={theme_data['primary'].replace('#', '#88')}
color13={theme_data['accent_colors'][0].replace('#', '#88') if theme_data['accent_colors'] else '#9b59b688'}
color14={theme_data['info'].replace('#', '#88')}
color15=#ffffff
"""

        # Создаем директорию если не существует
        self.termux_colors_dir.mkdir(parents=True, exist_ok=True)

        with open(colors_file, 'w') as f:
            f.write(colors_content)

        # Применение цветов
        cmd = "termux-reload-settings"
        self._execute_command(cmd)

    def _create_material_you_theme(self, theme_data):
        """Создание Material You темы."""
        # На основе https://github.com/FrancescoCaracciolo/material-you-colors
        material_you_theme = {
            "source_color": theme_data['primary'],
            "colors": {
                "primary": theme_data['primary'],
                "secondary": theme_data['secondary'],
                "tertiary": theme_data['accent_colors'][0] if theme_data['accent_colors'] else '',
                "error": theme_data['error'],
                "neutral": theme_data['background'],
                "neutral_variant": theme_data['surface']
            },
            "dark": theme_data['mode'] == 'dark'
        }

        theme_file = self.config_dir / 'material_you_theme.json'
        with open(theme_file, 'w') as f:
            json.dump(material_you_theme, f, indent=2)

        # Экспорт темы для использования другими приложениями
        export_dir = Path('/sdcard/Documents/Themes')
        if export_dir.exists():
            with open(export_dir / 'material_you_theme.json', 'w') as f:
                json.dump(material_you_theme, f, indent=2)

    def _apply_monet_engine(self, theme_data):
        """Применение через Monet (Android 12+)."""
        # Этот метод требует root или специальных разрешений
        # Здесь базовая реализация через терминал

        # Сохранение цветов Monet
        monet_colors = {
            "accent1": theme_data['primary'],
            "accent2": theme_data['secondary'],
            "accent3": theme_data['accent_colors'][0] if theme_data['accent_colors'] else '',
            "neutral1": theme_data['background'],
            "neutral2": theme_data['surface']
        }

        colors_file = self.config_dir / 'monet_colors.json'
        with open(colors_file, 'w') as f:
            json.dump(monet_colors, f, indent=2)

        # Попытка применить через команды (требует root)
        if self._check_root():
            self._apply_monet_root(monet_colors)

    def _apply_monet_root(self, monet_colors):
        """Применение Monet с root правами."""
        try:
            # Экспорт цветов Monet в системные настройки
            for i, (key, value) in enumerate(monet_colors.items(), 1):
                cmd = f"settings put system monet_engine_custom_color_{i} {value.replace('#', '')}"
                subprocess.run(['su', '-c', cmd], capture_output=True)

            # Включение кастомной темы
            cmd = "settings put system monet_engine_custom_theme 1"
            subprocess.run(['su', '-c', cmd], capture_output=True)

            logger.info("Monet тема применена (требуется root)")
            return True
        except:
            return False

    def set_wallpaper(self, wallpaper_path):
        """Установка обоев на Android."""
        if not Path(wallpaper_path).exists():
            logger.error(f"Файл обоев не найден: {wallpaper_path}")
            return False

        try:
            # Копируем обои в доступное место
            import shutil
            wallpapers_dir = Path('/sdcard/Pictures/Wallpapers')
            wallpapers_dir.mkdir(parents=True, exist_ok=True)

            dest_path = wallpapers_dir / Path(wallpaper_path).name
            shutil.copy2(wallpaper_path, dest_path)

            # Устанавливаем через termux-wallpaper
            cmd = f"termux-wallpaper -f {dest_path}"
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            if result.returncode == 0:
                logger.info(f"Обои установлены: {dest_path}")
                return True
            else:
                # Альтернативный метод
                cmd = f"am broadcast -a android.intent.action.ATTACH_DATA -d file://{dest_path} --ez setwallpaper true"
                subprocess.run(cmd, shell=True, capture_output=True)
                return True

        except Exception as e:
            logger.error(f"Ошибка установки обоев Android: {e}")
            return False

    def get_current_theme(self):
        """Получение текущей темы Android."""
        theme = {}

        try:
            # Пытаемся получить настройки Termux
            colors_file = self.termux_colors_dir / 'colors.properties'
            if colors_file.exists():
                with open(colors_file, 'r') as f:
                    for line in f:
                        if 'background' in line:
                            theme['background'] = line.split('=')[1].strip()
                        elif 'foreground' in line:
                            theme['foreground'] = line.split('=')[1].strip()

            return theme
        except Exception as e:
            logger.error(f"Ошибка получения темы Android: {e}")
            return {}

    def _check_root(self):
        """Проверка root прав."""
        try:
            result = subprocess.run(['su', '-c', 'id'], capture_output=True, text=True)
            return 'root' in result.stdout
        except:
            return False

    def refresh(self):
        """Обновление Android интерфейса."""
        # Перезагрузка SystemUI (требует root)
        if self._check_root():
            cmd = "pkill -f com.android.systemui"
            subprocess.run(['su', '-c', cmd], capture_output=True)